require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1 # Update this based on your Ruby version
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'config/**/*'
    - 'db/migrate/**/*'
  Metrics/LineLength:
    Max: 13 # Set maximum line length to 13

Rails:
  Enabled: true

RSpec:
  Enabled: true
